name: CI

on: [push, pull_request]

jobs:
  python-tests:
    name: Python Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Python tests
        run: python -m unittest discover

  matlab-tests:
    name: MATLAB Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v1
      - name: Run MATLAB tests
        run: matlab -batch "results = runtests; exit(any([results.Failed]));"
